# Generated by Django 4.0.6 on 2022-07-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='title2',
        ),
    ]
